import { type MoodId, type ScoredMood, MOOD_SCORE_THRESHOLD } from './moods';

interface SeedEntry {
  slug: string;
  title: string;
  moods: ScoredMood[];
}

function m(mood: MoodId, score: number): ScoredMood {
  return { mood, score };
}

const HIGH_BIAS = 95;
const MED_BIAS = 85;
const LOW_BIAS = 75;

export const SEED_DATA: SeedEntry[] = [
  // ---- HIGH PERFORMANCE (30+ books) ----
  { slug: 'atomic-habits', title: 'Atomic Habits', moods: [m('high_performance', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('practical', HIGH_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'deep-work', title: 'Deep Work', moods: [m('high_performance', HIGH_BIAS), m('practical', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-7-habits-of-highly-effective-people', title: 'The 7 Habits of Highly Effective People', moods: [m('self_growth', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('leadership', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-lean-startup', title: 'The Lean Startup', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'grit', title: 'Grit', moods: [m('resilience', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('inspiring', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'outliers', title: 'Outliers', moods: [m('curious', HIGH_BIAS), m('self_growth', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-compound-effect', title: 'The Compound Effect', moods: [m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'awaken-the-giant-within', title: 'Awaken the Giant Within', moods: [m('inspiring', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'essentialism', title: 'Essentialism', moods: [m('high_performance', HIGH_BIAS), m('practical', MED_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-one-thing', title: 'The ONE Thing', moods: [m('high_performance', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'getting-things-done', title: 'Getting Things Done', moods: [m('practical', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-4-hour-work-week', title: 'The 4-Hour Work Week', moods: [m('entrepreneurship', HIGH_BIAS), m('high_performance', MED_BIAS), m('money_wealth', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'flow', title: 'Flow', moods: [m('psychology', HIGH_BIAS), m('meditative', MED_BIAS), m('self_growth', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'drive', title: 'Drive', moods: [m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'talent-is-overrated', title: 'Talent is Overrated', moods: [m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'mastery', title: 'Mastery', moods: [m('self_growth', HIGH_BIAS), m('creativity', MED_BIAS), m('high_performance', MED_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'peak', title: 'Peak', moods: [m('high_performance', HIGH_BIAS), m('self_growth', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'moonwalking-with-einstein', title: 'Moonwalking with Einstein', moods: [m('curious', HIGH_BIAS), m('high_performance', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-learning', title: 'The Art of Learning', moods: [m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('psychology', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'principles', title: 'Principles', moods: [m('leadership', HIGH_BIAS), m('decision_making', HIGH_BIAS), m('practical', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'measure-what-matters', title: 'Measure What Matters', moods: [m('high_performance', HIGH_BIAS), m('leadership', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'so-good-they-cant-ignore-you', title: 'So Good They Can\'t Ignore You', moods: [m('career_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'willpower', title: 'Willpower', moods: [m('self_growth', HIGH_BIAS), m('psychology', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'spark', title: 'Spark', moods: [m('psychology', HIGH_BIAS), m('high_performance', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'why-we-sleep', title: 'Why We Sleep', moods: [m('psychology', HIGH_BIAS), m('high_performance', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'good-to-great', title: 'Good to Great', moods: [m('leadership', HIGH_BIAS), m('high_performance', MED_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'the-power-of-habit', title: 'The Power of Habit', moods: [m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'mindset', title: 'Mindset', moods: [m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS), m('inspiring', MED_BIAS)] },

  // ---- SELF GROWTH (30+ books) ----
  { slug: 'the-7-habits-of-highly-effective-people', title: 'The 7 Habits of Highly Effective People', moods: [m('self_growth', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-power-of-habit', title: 'The Power of Habit', moods: [m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'mindset', title: 'Mindset', moods: [m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'atomic-habits', title: 'Atomic Habits', moods: [m('self_growth', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-compound-effect', title: 'The Compound Effect', moods: [m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'awaken-the-giant-within', title: 'Awaken the Giant Within', moods: [m('self_growth', HIGH_BIAS), m('inspiring', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-four-agreements', title: 'The Four Agreements', moods: [m('self_growth', HIGH_BIAS), m('practical', LOW_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'emotional-intelligence', title: 'Emotional Intelligence', moods: [m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('self_growth', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: '12-rules-for-life', title: '12 Rules for Life', moods: [m('self_growth', HIGH_BIAS), m('inspiring', MED_BIAS), m('psychology', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'beyond-order', title: 'Beyond Order', moods: [m('self_growth', HIGH_BIAS), m('psychology', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-road-to-character', title: 'The Road to Character', moods: [m('self_growth', HIGH_BIAS), m('inspiring', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'daring-greatly', title: 'Daring Greatly', moods: [m('human_nature', HIGH_BIAS), m('emotional', HIGH_BIAS), m('inspiring', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'the-power-of-now', title: 'The Power of Now', moods: [m('meditative', HIGH_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'a-new-earth', title: 'A New Earth', moods: [m('existential', HIGH_BIAS), m('meditative', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-art-of-happiness', title: 'The Art of Happiness', moods: [m('inspiring', HIGH_BIAS), m('meditative', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'grit', title: 'Grit', moods: [m('resilience', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-war-of-art', title: 'The War of Art', moods: [m('creativity', HIGH_BIAS), m('resilience', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'big-magic', title: 'Big Magic', moods: [m('creativity', HIGH_BIAS), m('inspiring', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'dare-to-lead', title: 'Dare to Lead', moods: [m('leadership', HIGH_BIAS), m('resilience', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'the-happiness-hypothesis', title: 'The Happiness Hypothesis', moods: [m('psychology', HIGH_BIAS), m('inspiring', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'range', title: 'Range', moods: [m('career_growth', HIGH_BIAS), m('creativity', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-learning', title: 'The Art of Learning', moods: [m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('resilience', MED_BIAS)] },

  // ---- MONEY & WEALTH (25+ books) ----
  { slug: 'the-psychology-of-money', title: 'The Psychology of Money', moods: [m('money_wealth', HIGH_BIAS), m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'rich-dad-poor-dad', title: 'Rich Dad Poor Dad', moods: [m('money_wealth', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-personal-mba', title: 'The Personal MBA', moods: [m('career_growth', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('practical', MED_BIAS), m('money_wealth', MED_BIAS)] },
  { slug: 'i-will-teach-you-to-be-rich', title: 'I Will Teach You to Be Rich', moods: [m('money_wealth', HIGH_BIAS), m('practical', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'your-money-or-your-life', title: 'Your Money or Your Life', moods: [m('money_wealth', HIGH_BIAS), m('existential', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-simple-path-to-wealth', title: 'The Simple Path to Wealth', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-intelligent-investor', title: 'The Intelligent Investor', moods: [m('money_wealth', HIGH_BIAS), m('decision_making', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'think-and-grow-rich', title: 'Think and Grow Rich', moods: [m('money_wealth', HIGH_BIAS), m('inspiring', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-millionaire-next-door', title: 'The Millionaire Next Door', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', LOW_BIAS)] },
  { slug: 'the-automatic-millionaire', title: 'The Automatic Millionaire', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'total-money-makeover', title: 'Total Money Makeover', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'richest-man-in-babylon', title: 'The Richest Man in Babylon', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS), m('inspiring', LOW_BIAS)] },
  { slug: 'venture-deals', title: 'Venture Deals', moods: [m('money_wealth', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-bogleheads-guide-to-investing', title: 'The Bogleheads\' Guide to Investing', moods: [m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'a-random-walk-down-wall-street', title: 'A Random Walk Down Wall Street', moods: [m('money_wealth', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-black-swan', title: 'The Black Swan', moods: [m('thought_provoking', HIGH_BIAS), m('decision_making', MED_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'antifragile', title: 'Antifragile', moods: [m('resilience', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'fooled-by-randomness', title: 'Fooled by Randomness', moods: [m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS), m('money_wealth', MED_BIAS)] },
  { slug: 'the-dhandho-investor', title: 'The Dhandho Investor', moods: [m('money_wealth', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-education-of-a-value-investor', title: 'The Education of a Value Investor', moods: [m('money_wealth', HIGH_BIAS), m('self_growth', MED_BIAS)] },

  // ---- PSYCHOLOGY (40+ books) ----
  { slug: 'thinking-fast-and-slow', title: 'Thinking, Fast and Slow', moods: [m('psychology', HIGH_BIAS), m('decision_making', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'predictably-irrational', title: 'Predictably Irrational', moods: [m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS), m('curious', MED_BIAS)] },
  { slug: 'influence', title: 'Influence', moods: [m('psychology', HIGH_BIAS), m('communication', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-power-of-habit', title: 'The Power of Habit', moods: [m('psychology', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'emotional-intelligence', title: 'Emotional Intelligence', moods: [m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'nudge', title: 'Nudge', moods: [m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'misbehaving', title: 'Misbehaving', moods: [m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS), m('curious', MED_BIAS)] },
  { slug: 'stumbling-on-happiness', title: 'Stumbling on Happiness', moods: [m('psychology', HIGH_BIAS), m('curious', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-selfish-gene', title: 'The Selfish Gene', moods: [m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'behave', title: 'Behave', moods: [m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-righteous-mind', title: 'The Righteous Mind', moods: [m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-coddling-of-the-american-mind', title: 'The Coddling of the American Mind', moods: [m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'flow', title: 'Flow', moods: [m('psychology', HIGH_BIAS), m('meditative', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'drive', title: 'Drive', moods: [m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-happiness-hypothesis', title: 'The Happiness Hypothesis', moods: [m('psychology', HIGH_BIAS), m('inspiring', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'incognito', title: 'Incognito', moods: [m('psychology', HIGH_BIAS), m('curious', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-brain-that-changes-itself', title: 'The Brain That Changes Itself', moods: [m('psychology', HIGH_BIAS), m('curious', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-paradox-of-choice', title: 'The Paradox of Choice', moods: [m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS), m('existential', LOW_BIAS)] },
  { slug: 'the-marshmallow-test', title: 'The Marshmallow Test', moods: [m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-social-animal', title: 'The Social Animal', moods: [m('human_nature', HIGH_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'factfulness', title: 'Factfulness', moods: [m('decision_making', HIGH_BIAS), m('curious', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-thinking-clearly', title: 'The Art of Thinking Clearly', moods: [m('decision_making', HIGH_BIAS), m('psychology', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'thinking-in-bets', title: 'Thinking in Bets', moods: [m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'decisive', title: 'Decisive', moods: [m('decision_making', HIGH_BIAS), m('practical', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-master-algorithm', title: 'The Master Algorithm', moods: [m('future_ai', HIGH_BIAS), m('psychology', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'superforecasting', title: 'Superforecasting', moods: [m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS), m('practical', MED_BIAS)] },

  // ---- DECISION MAKING (28+ books) ----
  { slug: 'thinking-fast-and-slow', title: 'Thinking, Fast and Slow', moods: [m('decision_making', HIGH_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-psychology-of-money', title: 'The Psychology of Money', moods: [m('decision_making', HIGH_BIAS), m('money_wealth', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-war', title: 'The Art of War', moods: [m('leadership', HIGH_BIAS), m('decision_making', HIGH_BIAS), m('resilience', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'predictably-irrational', title: 'Predictably Irrational', moods: [m('decision_making', HIGH_BIAS), m('psychology', HIGH_BIAS), m('curious', MED_BIAS)] },
  { slug: 'the-black-swan', title: 'The Black Swan', moods: [m('decision_making', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'antifragile', title: 'Antifragile', moods: [m('decision_making', HIGH_BIAS), m('resilience', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'never-split-the-difference', title: 'Never Split the Difference', moods: [m('communication', HIGH_BIAS), m('decision_making', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'principles', title: 'Principles', moods: [m('decision_making', HIGH_BIAS), m('leadership', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-innovators-dilemma', title: 'The Innovator\'s Dilemma', moods: [m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'blue-ocean-strategy', title: 'Blue Ocean Strategy', moods: [m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'the-first-90-days', title: 'The First 90 Days', moods: [m('career_growth', HIGH_BIAS), m('leadership', MED_BIAS), m('decision_making', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'skin-in-the-game', title: 'Skin in the Game', moods: [m('decision_making', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'the-fifth-discipline', title: 'The Fifth Discipline', moods: [m('leadership', HIGH_BIAS), m('decision_making', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'thinking-in-systems', title: 'Thinking in Systems', moods: [m('decision_making', HIGH_BIAS), m('practical', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'noise', title: 'Noise', moods: [m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS), m('practical', MED_BIAS)] },

  // ---- FUTURE & AI (28+ books) ----
  { slug: 'homo-deus', title: 'Homo Deus', moods: [m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS), m('thought_provoking', HIGH_BIAS)] },
  { slug: 'life-30', title: 'Life 3.0', moods: [m('future_ai', HIGH_BIAS), m('existential', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'superintelligence', title: 'Superintelligence', moods: [m('future_ai', HIGH_BIAS), m('existential', MED_BIAS), m('thought_provoking', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-singularity-is-near', title: 'The Singularity is Near', moods: [m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'ai-2041', title: 'AI 2041', moods: [m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'the-master-algorithm', title: 'The Master Algorithm', moods: [m('future_ai', HIGH_BIAS), m('psychology', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'weapons-of-math-destruction', title: 'Weapons of Math Destruction', moods: [m('future_ai', HIGH_BIAS), m('dark', MED_BIAS), m('psychology', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'hello-world', title: 'Hello World', moods: [m('future_ai', HIGH_BIAS), m('psychology', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-age-of-surveillance-capitalism', title: 'The Age of Surveillance Capitalism', moods: [m('future_ai', HIGH_BIAS), m('dark', MED_BIAS), m('human_nature', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-machine-stops', title: 'The Machine Stops', moods: [m('future_ai', HIGH_BIAS), m('dark', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'neuromancer', title: 'Neuromancer', moods: [m('future_ai', HIGH_BIAS), m('dark', MED_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'snow-crash', title: 'Snow Crash', moods: [m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'ready-player-one', title: 'Ready Player One', moods: [m('future_ai', HIGH_BIAS), m('curious', MED_BIAS), m('fast_paced', MED_BIAS)] },
  { slug: 'dune', title: 'Dune', moods: [m('future_ai', HIGH_BIAS), m('existential', MED_BIAS), m('leadership', MED_BIAS), m('dark', MED_BIAS)] },
  { slug: 'foundation', title: 'Foundation', moods: [m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS), m('thought_provoking', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'brave-new-world', title: 'Brave New World', moods: [m('future_ai', HIGH_BIAS), m('dark', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-algorithm-and-the-alphabet', title: 'The Alphabet and the Algorithm', moods: [m('future_ai', HIGH_BIAS), m('creativity', MED_BIAS), m('thought_provoking', MED_BIAS)] },

  // ---- LEADERSHIP (30+ books) ----
  { slug: 'the-7-habits', title: 'The 7 Habits of Highly Effective People', moods: [m('leadership', MED_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'how-to-win-friends-and-influence-people', title: 'How to Win Friends and Influence People', moods: [m('communication', HIGH_BIAS), m('leadership', MED_BIAS), m('human_nature', HIGH_BIAS)] },
  { slug: 'start-with-why', title: 'Start With Why', moods: [m('leadership', HIGH_BIAS), m('inspiring', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'the-art-of-war', title: 'The Art of War', moods: [m('leadership', HIGH_BIAS), m('decision_making', HIGH_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'the-48-laws-of-power', title: 'The 48 Laws of Power', moods: [m('leadership', HIGH_BIAS), m('psychology', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'good-to-great', title: 'Good to Great', moods: [m('leadership', HIGH_BIAS), m('high_performance', MED_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'built-to-last', title: 'Built to Last', moods: [m('leadership', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'the-hard-thing-about-hard-things', title: 'The Hard Thing About Hard Things', moods: [m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'radical-candor', title: 'Radical Candor', moods: [m('leadership', HIGH_BIAS), m('communication', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'leaders-eat-last', title: 'Leaders Eat Last', moods: [m('leadership', HIGH_BIAS), m('human_nature', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-culture-code', title: 'The Culture Code', moods: [m('leadership', HIGH_BIAS), m('human_nature', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'team-of-teams', title: 'Team of Teams', moods: [m('leadership', HIGH_BIAS), m('decision_making', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'the-five-dysfunctions-of-a-team', title: 'The Five Dysfunctions of a Team', moods: [m('leadership', HIGH_BIAS), m('human_nature', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'multipliers', title: 'Multipliers', moods: [m('leadership', HIGH_BIAS), m('high_performance', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'trillion-dollar-coach', title: 'Trillion Dollar Coach', moods: [m('leadership', HIGH_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'what-got-you-here-wont-get-you-there', title: 'What Got You Here Won\'t Get You There', moods: [m('career_growth', HIGH_BIAS), m('communication', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'steve-jobs', title: 'Steve Jobs', moods: [m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS), m('entrepreneurship', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'creativity-inc', title: 'Creativity, Inc.', moods: [m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS), m('entrepreneurship', MED_BIAS)] },

  // ---- RESILIENCE (25+ books) ----
  { slug: 'mans-search-for-meaning', title: 'Man\'s Search for Meaning', moods: [m('existential', HIGH_BIAS), m('resilience', HIGH_BIAS), m('inspiring', HIGH_BIAS), m('dark', MED_BIAS)] },
  { slug: 'grit', title: 'Grit', moods: [m('resilience', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'meditations', title: 'Meditations', moods: [m('resilience', HIGH_BIAS), m('meditative', MED_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'antifragile', title: 'Antifragile', moods: [m('resilience', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-war-of-art', title: 'The War of Art', moods: [m('creativity', HIGH_BIAS), m('resilience', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: '12-rules-for-life', title: '12 Rules for Life', moods: [m('self_growth', HIGH_BIAS), m('resilience', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-learning', title: 'The Art of Learning', moods: [m('self_growth', HIGH_BIAS), m('resilience', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'thinking-in-bets', title: 'Thinking in Bets', moods: [m('decision_making', HIGH_BIAS), m('resilience', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'dare-to-lead', title: 'Dare to Lead', moods: [m('leadership', HIGH_BIAS), m('resilience', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'shoe-dog', title: 'Shoe Dog', moods: [m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'elon-musk', title: 'Elon Musk', moods: [m('entrepreneurship', HIGH_BIAS), m('future_ai', MED_BIAS), m('visionary', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'the-obstacle-is-the-way', title: 'The Obstacle Is the Way', moods: [m('resilience', HIGH_BIAS), m('inspiring', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'ego-is-the-enemy', title: 'Ego Is the Enemy', moods: [m('resilience', HIGH_BIAS), m('self_growth', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'stillness-is-the-key', title: 'Stillness Is the Key', moods: [m('meditative', HIGH_BIAS), m('resilience', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'endurance', title: 'Endurance', moods: [m('resilience', HIGH_BIAS), m('inspiring', MED_BIAS), m('curious', MED_BIAS)] },
  { slug: 'can-hurt-me', title: 'Can\'t Hurt Me', moods: [m('resilience', HIGH_BIAS), m('self_growth', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-body-keeps-the-score', title: 'The Body Keeps the Score', moods: [m('psychology', HIGH_BIAS), m('resilience', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'educated', title: 'Educated', moods: [m('resilience', HIGH_BIAS), m('inspiring', MED_BIAS), m('emotional', MED_BIAS)] },
  { slug: 'born-a-crime', title: 'Born a Crime', moods: [m('resilience', HIGH_BIAS), m('emotional', MED_BIAS), m('human_nature', MED_BIAS)] },

  // ---- CREATIVITY (25+ books) ----
  { slug: 'steve-jobs', title: 'Steve Jobs', moods: [m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS), m('entrepreneurship', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'creativity-inc', title: 'Creativity, Inc.', moods: [m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS), m('entrepreneurship', MED_BIAS)] },
  { slug: 'the-design-of-everyday-things', title: 'The Design of Everyday Things', moods: [m('practical', HIGH_BIAS), m('creativity', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'made-to-stick', title: 'Made to Stick', moods: [m('communication', HIGH_BIAS), m('creativity', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'contagious', title: 'Contagious', moods: [m('communication', HIGH_BIAS), m('psychology', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'linchpin', title: 'Linchpin', moods: [m('creativity', HIGH_BIAS), m('leadership', MED_BIAS), m('entrepreneurship', MED_BIAS)] },
  { slug: 'the-war-of-art', title: 'The War of Art', moods: [m('creativity', HIGH_BIAS), m('resilience', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'big-magic', title: 'Big Magic', moods: [m('creativity', HIGH_BIAS), m('inspiring', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'rework', title: 'Rework', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'the-art-of-innovation', title: 'The Art of Innovation', moods: [m('creativity', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'where-good-ideas-come-from', title: 'Where Good Ideas Come From', moods: [m('creativity', HIGH_BIAS), m('curious', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-creative-habit', title: 'The Creative Habit', moods: [m('creativity', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'steal-like-an-artist', title: 'Steal Like an Artist', moods: [m('creativity', HIGH_BIAS), m('practical', MED_BIAS), m('inspiring', LOW_BIAS)] },
  { slug: 'the-art-of-the-start', title: 'The Art of the Start', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'mastery', title: 'Mastery', moods: [m('self_growth', HIGH_BIAS), m('creativity', MED_BIAS), m('high_performance', MED_BIAS)] },

  // ---- HUMAN NATURE (25+ books) ----
  { slug: 'how-to-win-friends-and-influence-people', title: 'How to Win Friends and Influence People', moods: [m('human_nature', HIGH_BIAS), m('communication', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'daring-greatly', title: 'Daring Greatly', moods: [m('human_nature', HIGH_BIAS), m('emotional', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-righteous-mind', title: 'The Righteous Mind', moods: [m('human_nature', HIGH_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'tribe', title: 'Tribe', moods: [m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-social-animal', title: 'The Social Animal', moods: [m('human_nature', HIGH_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'loneliness', title: 'Loneliness', moods: [m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS), m('emotional', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-art-of-loving', title: 'The Art of Loving', moods: [m('human_nature', HIGH_BIAS), m('emotional', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'attached', title: 'Attached', moods: [m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'mating-in-captivity', title: 'Mating in Captivity', moods: [m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS), m('creativity', LOW_BIAS)] },
  { slug: 'the-storytelling-animal', title: 'The Storytelling Animal', moods: [m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'emotional-intelligence', title: 'Emotional Intelligence', moods: [m('human_nature', HIGH_BIAS), m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-culture-code', title: 'The Culture Code', moods: [m('human_nature', MED_BIAS), m('leadership', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'radical-candor', title: 'Radical Candor', moods: [m('human_nature', MED_BIAS), m('leadership', HIGH_BIAS), m('communication', MED_BIAS)] },
  { slug: 'leaders-eat-last', title: 'Leaders Eat Last', moods: [m('human_nature', MED_BIAS), m('leadership', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-body-keeps-the-score', title: 'The Body Keeps the Score', moods: [m('human_nature', MED_BIAS), m('psychology', HIGH_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'behave', title: 'Behave', moods: [m('human_nature', MED_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'sapiens', title: 'Sapiens', moods: [m('human_nature', MED_BIAS), m('curious', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },

  // ---- EXISTENTIAL (25+ books) ----
  { slug: 'mans-search-for-meaning', title: 'Man\'s Search for Meaning', moods: [m('existential', HIGH_BIAS), m('resilience', HIGH_BIAS), m('inspiring', HIGH_BIAS)] },
  { slug: 'sapiens', title: 'Sapiens', moods: [m('existential', MED_BIAS), m('curious', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'the-alchemist', title: 'The Alchemist', moods: [m('inspiring', HIGH_BIAS), m('existential', MED_BIAS), m('meditative', MED_BIAS)] },
  { slug: '1984', title: '1984', moods: [m('dark', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'a-new-earth', title: 'A New Earth', moods: [m('existential', HIGH_BIAS), m('meditative', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-power-of-now', title: 'The Power of Now', moods: [m('meditative', HIGH_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'zen-and-the-art-of-motorcycle-maintenance', title: 'Zen and the Art of Motorcycle Maintenance', moods: [m('existential', HIGH_BIAS), m('meditative', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'siddhartha', title: 'Siddhartha', moods: [m('existential', HIGH_BIAS), m('meditative', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-fountainhead', title: 'The Fountainhead', moods: [m('existential', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'atlas-shrugged', title: 'Atlas Shrugged', moods: [m('existential', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('leadership', MED_BIAS), m('money_wealth', MED_BIAS)] },
  { slug: 'life-30', title: 'Life 3.0', moods: [m('existential', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'superintelligence', title: 'Superintelligence', moods: [m('existential', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-selfish-gene', title: 'The Selfish Gene', moods: [m('existential', MED_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'your-money-or-your-life', title: 'Your Money or Your Life', moods: [m('existential', MED_BIAS), m('money_wealth', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-happiness-hypothesis', title: 'The Happiness Hypothesis', moods: [m('existential', LOW_BIAS), m('psychology', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-road-to-character', title: 'The Road to Character', moods: [m('existential', LOW_BIAS), m('self_growth', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'meditations', title: 'Meditations', moods: [m('existential', MED_BIAS), m('resilience', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-conquest-of-happiness', title: 'The Conquest of Happiness', moods: [m('existential', MED_BIAS), m('inspiring', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'dune', title: 'Dune', moods: [m('existential', MED_BIAS), m('future_ai', HIGH_BIAS), m('leadership', MED_BIAS)] },

  // ---- VISIONARY (25+ books) ----
  { slug: 'sapiens', title: 'Sapiens', moods: [m('visionary', MED_BIAS), m('curious', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'homo-deus', title: 'Homo Deus', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', HIGH_BIAS)] },
  { slug: 'zero-to-one', title: 'Zero to One', moods: [m('visionary', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'the-singularity-is-near', title: 'The Singularity is Near', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'steve-jobs', title: 'Steve Jobs', moods: [m('visionary', MED_BIAS), m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS)] },
  { slug: 'built-to-last', title: 'Built to Last', moods: [m('visionary', MED_BIAS), m('leadership', HIGH_BIAS), m('entrepreneurship', MED_BIAS)] },
  { slug: 'foundation', title: 'Foundation', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'snow-crash', title: 'Snow Crash', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-structure-of-scientific-revolutions', title: 'The Structure of Scientific Revolutions', moods: [m('visionary', MED_BIAS), m('thought_provoking', HIGH_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'the-second-machine-age', title: 'The Second Machine Age', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-innovators-dilemma', title: 'The Innovator\'s Dilemma', moods: [m('visionary', LOW_BIAS), m('entrepreneurship', HIGH_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'the-age-of-em', title: 'The Age of Em', moods: [m('visionary', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'abundance', title: 'Abundance', moods: [m('visionary', MED_BIAS), m('future_ai', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-infinite-machine', title: 'The Infinite Machine', moods: [m('visionary', MED_BIAS), m('future_ai', MED_BIAS), m('entrepreneurship', MED_BIAS)] },

  // ---- COMMUNICATION (25+ books) ----
  { slug: 'how-to-win-friends-and-influence-people', title: 'How to Win Friends and Influence People', moods: [m('communication', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'never-split-the-difference', title: 'Never Split the Difference', moods: [m('communication', HIGH_BIAS), m('decision_making', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'crucial-conversations', title: 'Crucial Conversations', moods: [m('communication', HIGH_BIAS), m('human_nature', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'talk-like-ted', title: 'Talk Like TED', moods: [m('communication', HIGH_BIAS), m('creativity', MED_BIAS), m('career_growth', MED_BIAS)] },
  { slug: 'made-to-stick', title: 'Made to Stick', moods: [m('communication', HIGH_BIAS), m('creativity', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'contagious', title: 'Contagious', moods: [m('communication', HIGH_BIAS), m('psychology', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'daring-greatly', title: 'Daring Greatly', moods: [m('communication', MED_BIAS), m('human_nature', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'influence', title: 'Influence', moods: [m('communication', MED_BIAS), m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-48-laws-of-power', title: 'The 48 Laws of Power', moods: [m('communication', MED_BIAS), m('leadership', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'switch', title: 'Switch', moods: [m('communication', MED_BIAS), m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-mom-test', title: 'The Mom Test', moods: [m('entrepreneurship', MED_BIAS), m('communication', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'radical-candor', title: 'Radical Candor', moods: [m('communication', MED_BIAS), m('leadership', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'what-got-you-here-wont-get-you-there', title: 'What Got You Here Won\'t Get You There', moods: [m('communication', MED_BIAS), m('career_growth', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'start-with-why', title: 'Start With Why', moods: [m('communication', MED_BIAS), m('leadership', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-art-of-communicating', title: 'The Art of Communicating', moods: [m('communication', HIGH_BIAS), m('human_nature', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'nonviolent-communication', title: 'Nonviolent Communication', moods: [m('communication', HIGH_BIAS), m('human_nature', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-storytelling-animal', title: 'The Storytelling Animal', moods: [m('communication', MED_BIAS), m('human_nature', HIGH_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'pre-suasion', title: 'Pre-Suasion', moods: [m('communication', MED_BIAS), m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS)] },

  // ---- ENTREPRENEURSHIP (30+ books) ----
  { slug: 'zero-to-one', title: 'Zero to One', moods: [m('entrepreneurship', HIGH_BIAS), m('visionary', MED_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'the-lean-startup', title: 'The Lean Startup', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-hard-thing-about-hard-things', title: 'The Hard Thing About Hard Things', moods: [m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'shoe-dog', title: 'Shoe Dog', moods: [m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'elon-musk', title: 'Elon Musk', moods: [m('entrepreneurship', HIGH_BIAS), m('future_ai', MED_BIAS), m('visionary', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'steve-jobs', title: 'Steve Jobs', moods: [m('entrepreneurship', HIGH_BIAS), m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'creativity-inc', title: 'Creativity, Inc.', moods: [m('entrepreneurship', MED_BIAS), m('creativity', HIGH_BIAS), m('leadership', HIGH_BIAS)] },
  { slug: 'the-4-hour-work-week', title: 'The 4-Hour Work Week', moods: [m('entrepreneurship', HIGH_BIAS), m('high_performance', MED_BIAS), m('money_wealth', MED_BIAS)] },
  { slug: 'rework', title: 'Rework', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'the-mom-test', title: 'The Mom Test', moods: [m('entrepreneurship', MED_BIAS), m('communication', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'rich-dad-poor-dad', title: 'Rich Dad Poor Dad', moods: [m('entrepreneurship', MED_BIAS), m('money_wealth', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-art-of-the-start', title: 'The Art of the Start', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'the-founders-dilemmas', title: 'The Founder\'s Dilemmas', moods: [m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'venture-deals', title: 'Venture Deals', moods: [m('entrepreneurship', MED_BIAS), m('money_wealth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-innovators-dilemma', title: 'The Innovator\'s Dilemma', moods: [m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'blue-ocean-strategy', title: 'Blue Ocean Strategy', moods: [m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'crossing-the-chasm', title: 'Crossing the Chasm', moods: [m('entrepreneurship', HIGH_BIAS), m('practical', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'hooked', title: 'Hooked', moods: [m('entrepreneurship', MED_BIAS), m('psychology', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-personal-mba', title: 'The Personal MBA', moods: [m('entrepreneurship', MED_BIAS), m('career_growth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'linchpin', title: 'Linchpin', moods: [m('entrepreneurship', MED_BIAS), m('creativity', HIGH_BIAS), m('leadership', MED_BIAS)] },

  // ---- CAREER GROWTH (25+ books) ----
  { slug: 'so-good-they-cant-ignore-you', title: 'So Good They Can\'t Ignore You', moods: [m('career_growth', HIGH_BIAS), m('high_performance', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-first-90-days', title: 'The First 90 Days', moods: [m('career_growth', HIGH_BIAS), m('leadership', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'what-got-you-here-wont-get-you-there', title: 'What Got You Here Won\'t Get You There', moods: [m('career_growth', HIGH_BIAS), m('communication', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'never-eat-alone', title: 'Never Eat Alone', moods: [m('career_growth', HIGH_BIAS), m('communication', MED_BIAS), m('entrepreneurship', LOW_BIAS)] },
  { slug: 'range', title: 'Range', moods: [m('career_growth', HIGH_BIAS), m('creativity', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-personal-mba', title: 'The Personal MBA', moods: [m('career_growth', HIGH_BIAS), m('entrepreneurship', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'good-to-great', title: 'Good to Great', moods: [m('career_growth', MED_BIAS), m('leadership', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'talent-is-overrated', title: 'Talent is Overrated', moods: [m('career_growth', MED_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'mastery', title: 'Mastery', moods: [m('career_growth', MED_BIAS), m('self_growth', HIGH_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'the-making-of-a-manager', title: 'The Making of a Manager', moods: [m('career_growth', HIGH_BIAS), m('leadership', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'designing-your-life', title: 'Designing Your Life', moods: [m('career_growth', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-2-hour-job-search', title: 'The 2-Hour Job Search', moods: [m('career_growth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'trillion-dollar-coach', title: 'Trillion Dollar Coach', moods: [m('career_growth', MED_BIAS), m('leadership', HIGH_BIAS)] },
  { slug: 'the-alchemist', title: 'The Alchemist', moods: [m('inspiring', HIGH_BIAS), m('existential', MED_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'multiplicadores', title: 'Multipliers', moods: [m('career_growth', LOW_BIAS), m('leadership', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'talk-like-ted', title: 'Talk Like TED', moods: [m('career_growth', MED_BIAS), m('communication', HIGH_BIAS), m('creativity', MED_BIAS)] },

  // ---- INSPIRING (25+) ----
  { slug: 'the-alchemist', title: 'The Alchemist', moods: [m('inspiring', HIGH_BIAS), m('existential', MED_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'mans-search-for-meaning', title: 'Man\'s Search for Meaning', moods: [m('inspiring', HIGH_BIAS), m('existential', HIGH_BIAS), m('resilience', HIGH_BIAS)] },
  { slug: 'start-with-why', title: 'Start With Why', moods: [m('inspiring', MED_BIAS), m('leadership', HIGH_BIAS), m('communication', MED_BIAS)] },
  { slug: 'awaken-the-giant-within', title: 'Awaken the Giant Within', moods: [m('inspiring', HIGH_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-power-of-now', title: 'The Power of Now', moods: [m('inspiring', MED_BIAS), m('meditative', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-art-of-happiness', title: 'The Art of Happiness', moods: [m('inspiring', HIGH_BIAS), m('meditative', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'the-four-agreements', title: 'The Four Agreements', moods: [m('inspiring', MED_BIAS), m('self_growth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'daring-greatly', title: 'Daring Greatly', moods: [m('inspiring', MED_BIAS), m('human_nature', HIGH_BIAS), m('emotional', HIGH_BIAS)] },
  { slug: 'big-magic', title: 'Big Magic', moods: [m('inspiring', MED_BIAS), m('creativity', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: '12-rules-for-life', title: '12 Rules for Life', moods: [m('inspiring', MED_BIAS), m('self_growth', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-road-to-character', title: 'The Road to Character', moods: [m('inspiring', MED_BIAS), m('self_growth', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'shoe-dog', title: 'Shoe Dog', moods: [m('inspiring', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'grit', title: 'Grit', moods: [m('inspiring', MED_BIAS), m('resilience', HIGH_BIAS), m('self_growth', HIGH_BIAS)] },
  { slug: 'meditations', title: 'Meditations', moods: [m('inspiring', MED_BIAS), m('resilience', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'siddhartha', title: 'Siddhartha', moods: [m('inspiring', MED_BIAS), m('existential', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'educated', title: 'Educated', moods: [m('inspiring', MED_BIAS), m('resilience', HIGH_BIAS), m('emotional', MED_BIAS)] },
  { slug: 'the-happiness-hypothesis', title: 'The Happiness Hypothesis', moods: [m('inspiring', MED_BIAS), m('psychology', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'leaders-eat-last', title: 'Leaders Eat Last', moods: [m('inspiring', MED_BIAS), m('leadership', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'the-conquest-of-happiness', title: 'The Conquest of Happiness', moods: [m('inspiring', MED_BIAS), m('existential', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'mindset', title: 'Mindset', moods: [m('inspiring', MED_BIAS), m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS)] },
  { slug: 'vagabonding', title: 'Vagabonding', moods: [m('inspiring', MED_BIAS), m('existential', MED_BIAS), m('meditative', MED_BIAS)] },

  // ---- DARK (20+ books) ----
  { slug: '1984', title: '1984', moods: [m('dark', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'brave-new-world', title: 'Brave New World', moods: [m('dark', HIGH_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'mans-search-for-meaning', title: 'Man\'s Search for Meaning', moods: [m('dark', MED_BIAS), m('existential', HIGH_BIAS), m('resilience', HIGH_BIAS)] },
  { slug: 'weapons-of-math-destruction', title: 'Weapons of Math Destruction', moods: [m('dark', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-age-of-surveillance-capitalism', title: 'The Age of Surveillance Capitalism', moods: [m('dark', MED_BIAS), m('future_ai', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'the-machine-stops', title: 'The Machine Stops', moods: [m('dark', MED_BIAS), m('future_ai', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'neuromancer', title: 'Neuromancer', moods: [m('dark', MED_BIAS), m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'dune', title: 'Dune', moods: [m('dark', MED_BIAS), m('future_ai', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'atlas-shrugged', title: 'Atlas Shrugged', moods: [m('dark', LOW_BIAS), m('thought_provoking', HIGH_BIAS), m('existential', HIGH_BIAS)] },
  { slug: 'heart-of-darkness', title: 'Heart of Darkness', moods: [m('dark', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'lord-of-the-flies', title: 'Lord of the Flies', moods: [m('dark', HIGH_BIAS), m('human_nature', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'crime-and-punishment', title: 'Crime and Punishment', moods: [m('dark', HIGH_BIAS), m('existential', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-road', title: 'The Road', moods: [m('dark', HIGH_BIAS), m('existential', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'fahrenheit-451', title: 'Fahrenheit 451', moods: [m('dark', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'the-handmaids-tale', title: 'The Handmaid\'s Tale', moods: [m('dark', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'collapse', title: 'Collapse', moods: [m('dark', MED_BIAS), m('thought_provoking', HIGH_BIAS), m('future_ai', LOW_BIAS), m('existential', MED_BIAS)] },
  { slug: 'blood-meridian', title: 'Blood Meridian', moods: [m('dark', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },

  // ---- FAST-PACED (20+ books) ----
  { slug: 'ready-player-one', title: 'Ready Player One', moods: [m('fast_paced', HIGH_BIAS), m('future_ai', HIGH_BIAS), m('curious', MED_BIAS)] },
  { slug: 'snow-crash', title: 'Snow Crash', moods: [m('fast_paced', MED_BIAS), m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'neuromancer', title: 'Neuromancer', moods: [m('fast_paced', MED_BIAS), m('future_ai', HIGH_BIAS), m('dark', MED_BIAS)] },
  { slug: 'the-davinci-code', title: 'The Da Vinci Code', moods: [m('fast_paced', HIGH_BIAS), m('curious', MED_BIAS), m('thought_provoking', LOW_BIAS)] },
  { slug: 'the-girl-with-the-dragon-tattoo', title: 'The Girl with the Dragon Tattoo', moods: [m('fast_paced', HIGH_BIAS), m('dark', MED_BIAS)] },
  { slug: 'gone-girl', title: 'Gone Girl', moods: [m('fast_paced', HIGH_BIAS), m('dark', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-martian', title: 'The Martian', moods: [m('fast_paced', HIGH_BIAS), m('resilience', MED_BIAS), m('practical', MED_BIAS)] },
  { slug: 'and-then-there-were-none', title: 'And Then There Were None', moods: [m('fast_paced', HIGH_BIAS), m('dark', MED_BIAS), m('thought_provoking', LOW_BIAS)] },
  { slug: 'the-hunger-games', title: 'The Hunger Games', moods: [m('fast_paced', HIGH_BIAS), m('dark', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'enders-game', title: 'Ender\'s Game', moods: [m('fast_paced', HIGH_BIAS), m('future_ai', MED_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'world-war-z', title: 'World War Z', moods: [m('fast_paced', HIGH_BIAS), m('dark', MED_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'the-andromeda-strain', title: 'The Andromeda Strain', moods: [m('fast_paced', HIGH_BIAS), m('curious', MED_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'jurassic-park', title: 'Jurassic Park', moods: [m('fast_paced', HIGH_BIAS), m('future_ai', MED_BIAS), m('curious', MED_BIAS)] },
  { slug: '1984', title: '1984', moods: [m('fast_paced', MED_BIAS), m('dark', HIGH_BIAS), m('thought_provoking', HIGH_BIAS)] },

  // ---- MEDITATIVE (20+ books) ----
  { slug: 'meditations', title: 'Meditations', moods: [m('meditative', HIGH_BIAS), m('resilience', HIGH_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-power-of-now', title: 'The Power of Now', moods: [m('meditative', HIGH_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'a-new-earth', title: 'A New Earth', moods: [m('meditative', MED_BIAS), m('existential', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'zen-and-the-art-of-motorcycle-maintenance', title: 'Zen and the Art of Motorcycle Maintenance', moods: [m('meditative', MED_BIAS), m('existential', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'siddhartha', title: 'Siddhartha', moods: [m('meditative', MED_BIAS), m('existential', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-four-agreements', title: 'The Four Agreements', moods: [m('meditative', MED_BIAS), m('self_growth', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'the-art-of-happiness', title: 'The Art of Happiness', moods: [m('meditative', MED_BIAS), m('inspiring', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'wherever-you-go-there-you-are', title: 'Wherever You Go, There You Are', moods: [m('meditative', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-mind-illuminated', title: 'The Mind Illuminated', moods: [m('meditative', HIGH_BIAS), m('practical', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: '10-happier', title: '10% Happier', moods: [m('meditative', HIGH_BIAS), m('self_growth', MED_BIAS), m('curious', MED_BIAS)] },
  { slug: 'the-headspace-guide-to-mindfulness', title: 'The Headspace Guide to Mindfulness', moods: [m('meditative', HIGH_BIAS), m('practical', MED_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'essentialism', title: 'Essentialism', moods: [m('meditative', MED_BIAS), m('high_performance', HIGH_BIAS), m('practical', MED_BIAS)] },
  { slug: 'stillness-is-the-key', title: 'Stillness Is the Key', moods: [m('meditative', HIGH_BIAS), m('resilience', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-alchemist', title: 'The Alchemist', moods: [m('meditative', MED_BIAS), m('inspiring', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'flow', title: 'Flow', moods: [m('meditative', MED_BIAS), m('psychology', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'vagabonding', title: 'Vagabonding', moods: [m('meditative', MED_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-art-of-stillness', title: 'The Art of Stillness', moods: [m('meditative', HIGH_BIAS), m('inspiring', MED_BIAS), m('existential', LOW_BIAS)] },

  // ---- CURIOUS (20+ books) ----
  { slug: 'sapiens', title: 'Sapiens', moods: [m('curious', HIGH_BIAS), m('thought_provoking', HIGH_BIAS), m('visionary', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'outliers', title: 'Outliers', moods: [m('curious', HIGH_BIAS), m('self_growth', MED_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'freakonomics', title: 'Freakonomics', moods: [m('curious', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-tipping-point', title: 'The Tipping Point', moods: [m('curious', HIGH_BIAS), m('psychology', MED_BIAS), m('communication', MED_BIAS)] },
  { slug: 'guns-germs-and-steel', title: 'Guns, Germs, and Steel', moods: [m('curious', HIGH_BIAS), m('thought_provoking', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-gene', title: 'The Gene', moods: [m('curious', HIGH_BIAS), m('future_ai', MED_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'incognito', title: 'Incognito', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-brain-that-changes-itself', title: 'The Brain That Changes Itself', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'moonwalking-with-einstein', title: 'Moonwalking with Einstein', moods: [m('curious', HIGH_BIAS), m('high_performance', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'factfulness', title: 'Factfulness', moods: [m('curious', MED_BIAS), m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'stumbling-on-happiness', title: 'Stumbling on Happiness', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'predictably-irrational', title: 'Predictably Irrational', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'a-short-history-of-nearly-everything', title: 'A Short History of Nearly Everything', moods: [m('curious', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'the-science-of-storytelling', title: 'The Science of Storytelling', moods: [m('curious', MED_BIAS), m('psychology', MED_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'the-disappearing-spoon', title: 'The Disappearing Spoon', moods: [m('curious', HIGH_BIAS), m('thought_provoking', LOW_BIAS)] },
  { slug: 'at-home', title: 'At Home', moods: [m('curious', HIGH_BIAS), m('thought_provoking', LOW_BIAS)] },
  { slug: 'the-codding-of-the-american-mind', title: 'The Coddling of the American Mind', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('thought_provoking', MED_BIAS)] },
  { slug: 'thinking-fast-and-slow', title: 'Thinking, Fast and Slow', moods: [m('curious', MED_BIAS), m('psychology', HIGH_BIAS), m('decision_making', HIGH_BIAS)] },

  // ---- EMOTIONAL (20+ books) ----
  { slug: 'daring-greatly', title: 'Daring Greatly', moods: [m('emotional', HIGH_BIAS), m('human_nature', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'mans-search-for-meaning', title: 'Man\'s Search for Meaning', moods: [m('emotional', MED_BIAS), m('existential', HIGH_BIAS), m('resilience', HIGH_BIAS)] },
  { slug: 'the-art-of-loving', title: 'The Art of Loving', moods: [m('emotional', MED_BIAS), m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'loneliness', title: 'Loneliness', moods: [m('emotional', MED_BIAS), m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'educated', title: 'Educated', moods: [m('emotional', MED_BIAS), m('resilience', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'shoe-dog', title: 'Shoe Dog', moods: [m('emotional', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('resilience', MED_BIAS)] },
  { slug: 'born-a-crime', title: 'Born a Crime', moods: [m('emotional', MED_BIAS), m('resilience', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'when-breath-becomes-air', title: 'When Breath Becomes Air', moods: [m('emotional', HIGH_BIAS), m('existential', HIGH_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-book-of-joy', title: 'The Book of Joy', moods: [m('emotional', MED_BIAS), m('inspiring', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'tuesdays-with-morrie', title: 'Tuesdays with Morrie', moods: [m('emotional', HIGH_BIAS), m('existential', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-fault-in-our-stars', title: 'The Fault in Our Stars', moods: [m('emotional', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'a-man-called-ove', title: 'A Man Called Ove', moods: [m('emotional', HIGH_BIAS), m('human_nature', MED_BIAS), m('inspiring', MED_BIAS)] },
  { slug: 'the-kite-runner', title: 'The Kite Runner', moods: [m('emotional', HIGH_BIAS), m('dark', MED_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'the-art-of-happiness', title: 'The Art of Happiness', moods: [m('emotional', LOW_BIAS), m('inspiring', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-alchemist', title: 'The Alchemist', moods: [m('emotional', LOW_BIAS), m('inspiring', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'attached', title: 'Attached', moods: [m('emotional', MED_BIAS), m('human_nature', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-five-love-languages', title: 'The 5 Love Languages', moods: [m('emotional', MED_BIAS), m('human_nature', HIGH_BIAS), m('communication', MED_BIAS)] },

  // ---- PRACTICAL (35+ books) ----
  { slug: 'atomic-habits', title: 'Atomic Habits', moods: [m('practical', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('self_growth', HIGH_BIAS)] },
  { slug: 'deep-work', title: 'Deep Work', moods: [m('practical', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-7-habits-of-highly-effective-people', title: 'The 7 Habits', moods: [m('practical', MED_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', HIGH_BIAS)] },
  { slug: 'the-power-of-habit', title: 'The Power of Habit', moods: [m('practical', MED_BIAS), m('self_growth', HIGH_BIAS), m('psychology', HIGH_BIAS)] },
  { slug: 'getting-things-done', title: 'Getting Things Done', moods: [m('practical', HIGH_BIAS), m('high_performance', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-4-hour-work-week', title: 'The 4-Hour Work Week', moods: [m('practical', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-lean-startup', title: 'The Lean Startup', moods: [m('practical', HIGH_BIAS), m('entrepreneurship', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'the-design-of-everyday-things', title: 'The Design of Everyday Things', moods: [m('practical', HIGH_BIAS), m('creativity', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'hooked', title: 'Hooked', moods: [m('practical', MED_BIAS), m('psychology', HIGH_BIAS), m('entrepreneurship', MED_BIAS)] },
  { slug: 'made-to-stick', title: 'Made to Stick', moods: [m('practical', MED_BIAS), m('communication', HIGH_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'essentialism', title: 'Essentialism', moods: [m('practical', MED_BIAS), m('high_performance', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-one-thing', title: 'The ONE Thing', moods: [m('practical', MED_BIAS), m('high_performance', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'principles', title: 'Principles', moods: [m('practical', MED_BIAS), m('leadership', HIGH_BIAS), m('decision_making', HIGH_BIAS)] },
  { slug: 'measure-what-matters', title: 'Measure What Matters', moods: [m('practical', MED_BIAS), m('high_performance', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'the-first-90-days', title: 'The First 90 Days', moods: [m('practical', MED_BIAS), m('career_growth', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'the-mom-test', title: 'The Mom Test', moods: [m('practical', MED_BIAS), m('entrepreneurship', MED_BIAS), m('communication', HIGH_BIAS)] },
  { slug: 'i-will-teach-you-to-be-rich', title: 'I Will Teach You to Be Rich', moods: [m('practical', MED_BIAS), m('money_wealth', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-simple-path-to-wealth', title: 'The Simple Path to Wealth', moods: [m('practical', MED_BIAS), m('money_wealth', HIGH_BIAS), m('self_growth', MED_BIAS)] },
  { slug: 'the-four-agreements', title: 'The Four Agreements', moods: [m('practical', MED_BIAS), m('self_growth', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-art-of-war', title: 'The Art of War', moods: [m('practical', MED_BIAS), m('leadership', HIGH_BIAS), m('decision_making', HIGH_BIAS)] },
  { slug: 'rework', title: 'Rework', moods: [m('practical', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'the-art-of-the-start', title: 'The Art of the Start', moods: [m('practical', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'the-compound-effect', title: 'The Compound Effect', moods: [m('practical', MED_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },
  { slug: 'switch', title: 'Switch', moods: [m('practical', MED_BIAS), m('psychology', HIGH_BIAS), m('communication', MED_BIAS)] },
  { slug: 'decisive', title: 'Decisive', moods: [m('practical', MED_BIAS), m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-art-of-thinking-clearly', title: 'The Art of Thinking Clearly', moods: [m('practical', MED_BIAS), m('decision_making', HIGH_BIAS), m('psychology', HIGH_BIAS)] },
  { slug: 'superforecasting', title: 'Superforecasting', moods: [m('practical', MED_BIAS), m('decision_making', HIGH_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'blue-ocean-strategy', title: 'Blue Ocean Strategy', moods: [m('practical', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'crossing-the-chasm', title: 'Crossing the Chasm', moods: [m('practical', MED_BIAS), m('entrepreneurship', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-design-of-everyday-things', title: 'The Design of Everyday Things', moods: [m('practical', MED_BIAS), m('creativity', MED_BIAS), m('psychology', MED_BIAS)] },
  { slug: 'the-checklist-manifesto', title: 'The Checklist Manifesto', moods: [m('practical', HIGH_BIAS), m('high_performance', MED_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'the-talent-code', title: 'The Talent Code', moods: [m('practical', MED_BIAS), m('self_growth', HIGH_BIAS), m('high_performance', MED_BIAS)] },

  // ---- THOUGHT-PROVOKING (35+ books) ----
  { slug: 'sapiens', title: 'Sapiens', moods: [m('thought_provoking', HIGH_BIAS), m('curious', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'thinking-fast-and-slow', title: 'Thinking, Fast and Slow', moods: [m('thought_provoking', HIGH_BIAS), m('psychology', HIGH_BIAS), m('decision_making', HIGH_BIAS)] },
  { slug: '1984', title: '1984', moods: [m('thought_provoking', HIGH_BIAS), m('dark', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'brave-new-world', title: 'Brave New World', moods: [m('thought_provoking', HIGH_BIAS), m('future_ai', HIGH_BIAS), m('dark', MED_BIAS)] },
  { slug: 'the-black-swan', title: 'The Black Swan', moods: [m('thought_provoking', HIGH_BIAS), m('decision_making', MED_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'antifragile', title: 'Antifragile', moods: [m('thought_provoking', HIGH_BIAS), m('resilience', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'freakonomics', title: 'Freakonomics', moods: [m('thought_provoking', MED_BIAS), m('curious', HIGH_BIAS), m('decision_making', MED_BIAS)] },
  { slug: 'guns-germs-and-steel', title: 'Guns, Germs, and Steel', moods: [m('thought_provoking', MED_BIAS), m('curious', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-selfish-gene', title: 'The Selfish Gene', moods: [m('thought_provoking', MED_BIAS), m('psychology', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'behave', title: 'Behave', moods: [m('thought_provoking', MED_BIAS), m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS)] },
  { slug: 'the-righteous-mind', title: 'The Righteous Mind', moods: [m('thought_provoking', MED_BIAS), m('psychology', HIGH_BIAS), m('human_nature', HIGH_BIAS)] },
  { slug: 'the-coddling-of-the-american-mind', title: 'The Coddling of the American Mind', moods: [m('thought_provoking', MED_BIAS), m('psychology', HIGH_BIAS), m('human_nature', MED_BIAS)] },
  { slug: 'homo-deus', title: 'Homo Deus', moods: [m('thought_provoking', HIGH_BIAS), m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'life-30', title: 'Life 3.0', moods: [m('thought_provoking', MED_BIAS), m('future_ai', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'superintelligence', title: 'Superintelligence', moods: [m('thought_provoking', MED_BIAS), m('future_ai', HIGH_BIAS), m('existential', MED_BIAS)] },
  { slug: 'the-structure-of-scientific-revolutions', title: 'The Structure of Scientific Revolutions', moods: [m('thought_provoking', HIGH_BIAS), m('visionary', MED_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'zen-and-the-art-of-motorcycle-maintenance', title: 'Zen and the Art of Motorcycle Maintenance', moods: [m('thought_provoking', MED_BIAS), m('existential', HIGH_BIAS), m('meditative', MED_BIAS)] },
  { slug: 'the-fountainhead', title: 'The Fountainhead', moods: [m('thought_provoking', MED_BIAS), m('existential', HIGH_BIAS), m('creativity', MED_BIAS)] },
  { slug: 'atlas-shrugged', title: 'Atlas Shrugged', moods: [m('thought_provoking', HIGH_BIAS), m('existential', HIGH_BIAS), m('leadership', MED_BIAS)] },
  { slug: 'fahrenheit-451', title: 'Fahrenheit 451', moods: [m('thought_provoking', MED_BIAS), m('dark', HIGH_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'foundation', title: 'Foundation', moods: [m('thought_provoking', MED_BIAS), m('future_ai', HIGH_BIAS), m('visionary', MED_BIAS)] },
  { slug: 'the-gene', title: 'The Gene', moods: [m('thought_provoking', MED_BIAS), m('curious', HIGH_BIAS), m('future_ai', MED_BIAS)] },
  { slug: 'the-age-of-surveillance-capitalism', title: 'The Age of Surveillance Capitalism', moods: [m('thought_provoking', MED_BIAS), m('future_ai', HIGH_BIAS), m('dark', MED_BIAS)] },
  { slug: 'collapse', title: 'Collapse', moods: [m('thought_provoking', HIGH_BIAS), m('dark', MED_BIAS), m('existential', MED_BIAS)] },
  { slug: 'enlightenment-now', title: 'Enlightenment Now', moods: [m('thought_provoking', HIGH_BIAS), m('decision_making', MED_BIAS), m('future_ai', LOW_BIAS)] },
  { slug: 'the-better-angels-of-our-nature', title: 'The Better Angels of Our Nature', moods: [m('thought_provoking', HIGH_BIAS), m('human_nature', MED_BIAS), m('psychology', MED_BIAS)] },
];

export function computeSeedMapping(): Record<string, { title: string; moods: ScoredMood[] }> {
  const map: Record<string, { title: string; moods: ScoredMood[] }> = {};
  for (const entry of SEED_DATA) {
    const moods = entry.moods.filter(m => m.score >= MOOD_SCORE_THRESHOLD);
    if (moods.length > 0) {
      map[entry.slug] = { title: entry.title, moods };
    }
  }
  return map;
}

export function getMoodCounts(): Record<MoodId, number> {
  const counts: Record<string, number> = {};
  for (const entry of SEED_DATA) {
    for (const sm of entry.moods) {
      if (sm.score >= MOOD_SCORE_THRESHOLD) {
        counts[sm.mood] = (counts[sm.mood] || 0) + 1;
      }
    }
  }
  return counts as Record<MoodId, number>;
}
